### PR TITLE
Update maintainers

### PR DESCRIPTION
**Pull request by porridge**
Not sure if @mpereira would like to be removed now...

### CODE REVIEW

**Comment by mpereira** [comment]
Feel free to leave me in. I still silently check the PRs... 😉

**Comment by zmalik** [comment]
we missed updating `operator.template`

**Comment by porridge** [comment]
Sorry for that. I must have confused the CI job results, because I was pretty sure that I'm overriding a flake due to cluster turn-up failure. :man_facepalming:

**Comment by porridge** [comment]
Thank you for fixing that in https://github.com/mesosphere/kudo-cassandra-operator/pull/145/files?file-filters%5B%5D=.template#diff-2fb17d45d0629056ee6a7d25af651615 @zmalik !

**Pull request merged**
