### PR TITLE
Fix Grafana dashboard for Prometheus metrics.

### PR DESCRIPTION
**Pull request by phrynchanka**
Fixed Grafana json from https://github.com/criteo/cassandra_exporter/blob/master/grafana/cassandra_kubernetes.json

### CODE REVIEW

**Comment by mpereira** [comment]
Thanks @phrynchanka.

Would you be able to attach a screenshot of the dashboard's graphs working?

**Comment by phrynchanka** [comment]
> Thanks @phrynchanka.
> 
> Would you be able to attach a screenshot of the dashboard's graphs working?

Sure. I've run stress test to see graphs.
---
cassandra_grafana

**Comment by mpereira** [comment]
Thanks @phrynchanka, that looks better.

I wonder if the graphs that show up empty are like that because there's really no metrics for them, or because their query is incorrect. Do you have an idea?

**Comment by mpereira** [comment]
I'm gonna merge this for now so that we have the dashboard in the repository. We can work on investigating why some graphs are empty later.

**Pull request merged**
